# Generated by Django 5.0.2 on 2024-04-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_alter_facility_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
