# Generated by Django 5.0.2 on 2024-04-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
