# Generated by Django 5.0.2 on 2024-04-21 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_room_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='rating',
        ),
    ]
